CUDA_VISIBLE_DEVICES=1 \
swift sft \
    --model /your/path/to/Gemma-3-4b-it \
    --train_type lora \
    --dataset /your/path/to/dataset \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --learning_rate 5e-4 \
    --lora_rank 64 \
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --target_modules all-linear \
    --gradient_accumulation_steps 8 \
    --save_strategy epoch \
    --save_total_limit 1 \
    --logging_steps 1 \
    --max_length 4096 \
    --output_dir output/\
    --weight_decay 0.1 \
    --warmup_ratio 0.05 \
    --lr_scheduler_type "cosine" \
    --dataloader_num_workers 4 \
    --report_to none \
    --attn_impl flash_attn\
    --model_type gemma3_vision